- .changeset/real-mangos-call.md
- packages/magento-customer/components/SignOutForm/SignOutForm.tsx
- packages/magento-customer/typePolicies.ts
The first none cached query eventually triggered the purge
All pages between logout and that first query were displaying an incorrect user state
> fix: persitence layer not being purged after logout

- .changeset/tiny-jokes-wonder.md
- packages/next-ui/Form/Form.tsx
Prevents ```Invalid value for prop `sx` on <form> tag.``` error
> fix: prevent sx prop from being passed to form element

- .changeset/lazy-onions-join.md
- packages/magento-customer-order/components/OrderCard/OrderCard.tsx
Die 88px komt uit packages/magento-customer-order/components/OrderCardItemImage/OrderCardItemImage.tsx:24
> fix: if recent order images > 1, images now actually show

- .changeset/stale-dryers-shake.md
- packages/magento-wishlist/components/ProductWishlistChip/ProductWishlistChip.graphql
This is old code from before the split into a chip base and multiple composition layers
It is now in the way when data is passed in without a typename
> fix: __typename is mandatory as wishlistchip prop value

- .changeset/breezy-paws-pump.md
- packages/magento-search/components/SearchForm/SearchForm.tsx
Does not work on iOS, as setting focus programmatically is not allowed on iOS Safari
> Set focus on search input when loading search page

- .changeset/funny-ligers-laugh.md
- packages/next-ui/Navigation/components/NavigationItem.tsx
Prevents the drill-down menu from breaking on smaller screens
> add media query guard to category menu behaviour.

- .changeset/plenty-hairs-laugh.md
- examples/magento-graphcms/.changeset/fast-pens-sing.md
- examples/magento-graphcms/pages/[...url].tsx
- packages/magento-category/components/CategoryMeta/CategoryMeta.tsx
Option to not require meta tags for categories. 
This may be handy when you want to add something to the page in Hygraph, but still want to get the meta tags from Magento.
> Option to not require meta tags for categories

- .changeset/slimy-kangaroos-report.md
- packages/next-ui/Overlay/components/OverlayBase.tsx
This prevent scrolling Android browser UI in and out of view causing the browser to resize, which in turn causes the bottom overlay to jump around
> Fix scroll issue with bottom overlay on Android

- .changeset/thin-guests-fetch.md
- packages/next-ui/Footer/Footer.tsx
to prevent cart fab overlapping footer content
> fix(GCOM-947): show mobile footer on tablet

- .changeset/lemon-houses-sit.md
- packages/magento-product-configurable/components/ConfigurableOptionValueText/ConfigurableOptionValueText.tsx
500 error: https://graphcommerce.vercel.app/p/configurable-without-swatches
fixed: https://graphcommerce-git-fix-various-graphcommerce.vercel.app/p/configurable-without-swatches
> ConfigurableProduct super attributes that were regular dropdowns would throw an error

- .changeset/fresh-icons-wait.md
- packages/magento-customer/components/SignUpForm/SignUpFormInline.tsx
> chore: enable password fields when there is an error and user input correction is required

- .changeset/three-turkeys-cross.md
- examples/magento-graphcms/next.config.js
We don't use this, and this ensures jest-worker isn't used which can cause issues in standalone mode. See also https://github.com/vercel/next.js/issues/45508
> Disable appDir

- .changeset/gentle-crews-fetch.md
- .changeset/perfect-buckets-talk.md
- .changeset/perfect-jeans-sell.md
- docs/framework/config.md
- examples/magento-graphcms/pages/p/[url].tsx
- packages/demo-magento-graphcommerce/graphql/demo/DemoProductPageItem.graphql
- packages/magento-product-configurable/Config.graphqls
- packages/magento-product-configurable/graphql/ConfigurableOptions.graphql
- packages/magento-product-configurable/graphql/ConfiguredVariant.graphql
- packages/magento-product-configurable/utils/defaultConfigurableOptionsSelection.ts
- packagesDev/next-config/dist/config/demoConfig.js
- packagesDev/next-config/dist/generated/config.js
- packagesDev/next-config/src/config/demoConfig.ts
- packagesDev/next-config/src/generated/config.ts
In this PR: 
**1. Improve defaultConfigurableOptionsSelection functionality**
_Situation: You land on a simple product page._ 
In the current main branch, we check all the configurableOptions of the linked configurable item. If a simple product does not have this option as a property on it's product branch, the option can not be configured on the simple product page. To fix this, you had to query that option in your productPage query to make it a property on the simple product. This however meant that you had to add a property to your query every time a site owner made a new configurable option. This is not dynamic nor scalable. 
To fix this:
We check the variants of a configurable option and match the variant SKU's with the SKU of the current simple product. When we know which variant …
> Feature/gcom 1120 | Improve defaultConfigurableOptionsSelection functionality 

- .changeset/dirty-toes-breathe.md
- packages/framer-scroller/components/Scroller.tsx
- packages/framer-scroller/hooks/useScroller.ts
Added event.preventDefault() because firefox did noice the onPan eventhandler and because of that it dragged the picture instead of swiped the scroller.
> bug(GCOM-1114) added onMouseDown eventhandler

- .changeset/new-toys-invent.md
- packages/algolia-search/hooks/useAlgoliaSearchIndexConfig.ts
- packages/algolia-search/plugins/AlgoliaProductSortPlugin.tsx
- packages/magento-product-configurable/components/ConfigurableProductOptions/ConfigurableProductOptions.tsx
- packages/next-ui/hooks/useDateTimeFormat.ts
- packages/next-ui/hooks/useNumberFormat.ts
- packagesDev/next-config/dist/withGraphCommerce.js
- packagesDev/next-config/src/withGraphCommerce.ts
These changes allow the use of locales such as `nl-nl-mystore`, `nl-nl-foostore`, etc. in next to connect with different Magento stores which have the same locale (i.e. `nl-nl`), but where i18n features (routing, translations, formatting etc) still works as expected.
In addition there are some fixes that make i18n domain routing work. You must set the `domain` field in your `GraphCommerceStorefrontConfig` config for this to function. You will also likely want to disable locale auto-redirection (`nextConfig.i18n.localeDetection`)
Some TODOs in this PR:
- Documentation (example setup)
- Test if/how `www.` subdomains work
- General testing
> Allow duplicate Magento store locales

- .changeset/healthy-spoons-doubt.md
- packages/magento-product-configurable/utils/defaultConfigurableOptionsSelection.ts
When configurableVariantForSimple = false, show simple layout. This was done by modifying the products.items array that we only use the items that have the same urlKey as productpage
https://hoproj.atlassian.net/browse/GCOM-1230
ConfigurableVariantForSimple = false still shows a configurable page on a simple
Canary
[Backend](https://backend.reachdigital.dev/admin_1wwdkh/catalog/product/edit/id/45689/key/c6b8e37f9266cf6e3bfa44ed8adb9c3eed2230386698ea77952032f8ae594384/)
[Productpage](https://graphcommerce.vercel.app/p/super-squeaky-size-4-6y-gc-468-sock-6yp/spooky-girl-size-4-6y-gc-1-sock-6y)
[Backend](https://backend.reachdigital.dev/admin_1wwdkh/catalog/product/edit/id/45693/key/c6b8e37f9266cf6e3bfa44ed8adb9c3eed2230386698ea77952032f8ae594384/) …
> [GCOM-1230] configurableVariantForSimple fix

- .changeset/real-garlics-battle.md
- packages/magento-cart-payment-method/PaymentMethodButton/PaymentMethodButton.tsx
| Before | After |
|--------|--------|
| ![localhost_3000_checkout_payment(iPhone 12 Pro) (1)](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/f52c2127-2b60-444a-9e84-39d135384506) | ![localhost_3000_checkout_payment(iPhone 12 Pro) (2)](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/b7c23d6f-3c2d-4ba2-9c16-84954722483b) |
> Decrease the fontSize for the payment button in the checkout to ensure the text fits within the button (GCOM-1186)

- .changeset/little-shirts-film.md
- packages/hygraph-ui/components/RichText/RichText.tsx
- packages/hygraph-ui/components/RichText/defaultRenderers.tsx
- packages/hygraph-ui/components/RichText/types.ts
Previously, when adding a CSS class to a node in Hygraph:
This would result in an error:
Now this no longer throws an error and applies the classes instead.
> feat(GCOM-1190): add renderer to support rendering Hygraph elements with a CSS class

- .changeset/quiet-tomatoes-melt.md
- docs/framework/config.md
- examples/magento-graphcms/pages/checkout/added.tsx
- packages/magento-cart/components/CartAdded/index.ts
- packages/magento-cart/components/CartAdded/useCrosssellItems.ts
- packages/magento-product/Config.graphqls
- packages/magento-product/components/AddProductsToCart/AddProductsToCartButton.tsx
- packages/magento-product/components/AddProductsToCart/AddProductsToCartFab.tsx
- packages/magento-product/components/AddProductsToCart/AddProductsToCartForm.tsx
- packages/magento-product/components/AddProductsToCart/AddProductsToCartSnackbar.tsx
- packages/magento-product/components/AddProductsToCart/useAddProductsToCartAction.ts
- packages/react-hook-form/src/useFormGql.tsx
- packagesDev/next-config/dist/generated/config.js
- packagesDev/next-config/src/generated/config.ts
- yarn.lock
[In this ticket](https://hoproj.atlassian.net/browse/GCOM-1138) implemented a more desirable behavior of the related products, inspired by wishes from [KOM-442](https://hoproj.atlassian.net/browse/KOM-442)
first check: @bramvanderholst 
second check: @paales 
**Magento Product**
- Crosssells should remain visible after add to cart. Do not pop away.
- Checkmark icon after add to cart added. showSuccess prop based on snack bar.
- Redirect default behavior off
- Correct product name to snackbar message after add crosssell product.
- Configure whether we want to redirect?
- Configure whether we want to filter out products that are in your cart?
**React hook form**
- add onComplete to RHF 
- add SubmittedVariables to RHF 
**Test**
/p/fuzzy-sticky-things-gc-691-sock
[KOM-442]: …
> Crosssells improvements (GCOM-1138)

- .changeset/tall-spies-reflect.md
- packages/magento-customer/components/EditAddressForm/EditAddressForm.tsx
- [GCOM Ticket](https://hoproj.atlassian.net/browse/GCOM-1266)
- [On request of Bouwprofi](https://hoproj.atlassian.net/browse/BPGC-215)
Magento gave an internal error when addition field was null or undefined. This was a magento bug but simply fixed by sending an empty string if addition is not given
> [GCOM-1266] Fix editAddressForm when addition is nullable

- .changeset/lazy-seahorses-rhyme.md
- packages/magento-cart/components/CartFab/CartFab.graphql
- packages/magento-cart/components/CartFab/CartFab.tsx
- packages/magento-cart/typePolicies.ts
We need to create a cache entry to read it on the next reload. This change helps us store the 'total_quantity' data in cache, so we can read it again when needed.
Now, when a guest adds products to their cart and refreshes the page, the cart will still show what's in it. It won't be empty.
**Current state (Empty cart after page refresh):**
https://app.birdeatsbug.com/FTOieYax2X1CIARxbnf6DipqxDh5rVo9koyxckWrBSSb
**New state (No empty cart after page refresh):**
https://app.birdeatsbug.com/KpE-ExYKlW7PYdwxnugfiO6j-Sougwyo1Eu2pC5-UU5b
> Use 'cache-first' fetch mode for getting 'total_quantity' data (GCOM-1241)

- .changeset/friendly-dogs-shop.md
- docs/magento/known-issues.md
- docs/magento/readme.md
This keeps the overview free of clutter, keeps the 'Next steps' section
at the bottom.
> Split off known issues to separate page

- .changeset/rotten-lions-chew.md
- packages/magento-customer/hooks/useAccountSignInUpForm.tsx
- packages/magento-customer/package.json
- yarn.lock
This is pretty bare-bones right now. It just logs you in and returns you to the previous page.
It feels pretty frictionless to me, but might be lacking in feedback a little bit?
Having a sceen with "You're now logg in. [Continue shopping]" is clear but does not really add much either. 
Redirecting to the account page after logging in also feels pretty silly.
This might be one of those things that feels unnatural at first, but I think it provides value by effortlessly continuing what you were doing before logging in. Therefore it might feel right pretty fast.
Thanks for reading this long essay about a trivial issue, have a great day!
> feat(GCOM-1318): dismiss login page and go back to previous page asap when logging in

- .changeset/dull-goats-cheat.md
- packages/next-ui/LazyHydrate/LazyHydrate.tsx
There are situations where you want to add HTML attributes to the component, for example adding a  specific`class` or `ID`.
> Allow and pass HTML attributes via the Lazyhydrate component

- .changeset/lucky-lizards-taste.md
- packages/magento-cart-shipping-method/components/ShippingMethodForm/ShippingMethodActionCard.tsx
| Before | After |
|--------|--------|
| ![image](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/e1683e7e-5de5-4abc-89a5-1c77bb2021e5) | ![image](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/3e996a12-4499-46a9-8e2f-96da71a644d2) |
> fix: prevent rendering 'null' when method_title is not provided

- .changeset/nine-poets-appear.md
- packages/magento-cart/components/CartAgreementsForm/CartAgreementsForm.tsx
In the current state it's not possible to insert 'custom' links into the 'checkbox_text' field.In certain scenarios, users may need to link to multiple terms and conditions (e.g. consumer or business).
| Magento | Before | After |
|--------|--------|--------|
| ![image](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/7d6ebdd8-4853-4964-a2ab-5b4ceecc6e08) | ![image](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/76ec999f-f556-455f-929b-9d13918f4e1c) | ![image](https://github.com/graphcommerce-org/graphcommerce/assets/62989724/180f43d4-d360-4290-97cb-683073b4365c) |
> fix: Enable the use of one or more anchor links within the Terms and conditions label field and customize their paths. (GCOM-1384)

- .changeset/rare-shoes-carry.md
- packages/magento-payment-included/methods.tsx
Place order button would show a spinner, but nothing would happen. No queries would fire. because the method `PaymentMethodPlaceOrderNoop` was undefined, due to a circular dependency
> Fixed Place order button not working (in dev mode) for certain payment methods

- .changeset/chilly-readers-enjoy.md
- packages/next-ui/FramerScroller/SidebarGallery.tsx
In some cases, you may want to add specific data to the SidebarGallery, such as custom labels or other information. Currently, it is only possible to send data via the children, but this data ends up in the sidebar where the product information (title, description, add to cart) is displayed.
> Add the possibility to place content before or after the scroller in the SidebarGallery (GCOM-1454)

- .changeset/witty-carpets-flow.md
- packages/magento-customer/components/AddressSingleLine/AddressSingleLine.tsx
**countryName**
When the page is loaded, the CountryRegions query is executed. Until then, the countryName is displayed as 'undefined'.
**regionName**
When you save an address without a 'region', it shows as 'undefined' in the `<AddressSingleLine />`. This also occurs when there is no option to fill in a 'region'.
> chore: avoid displaying 'undefined' for countryName or regionName

- .changeset/hungry-balloons-divide.md
- packages/magento-review/components/JsonLdProductReview/jsonLdProductReview.ts
| Error | Before | After |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/6dbc1f94-c18e-40f1-b7c4-758c635353d2) | ![image](https://github.com/user-attachments/assets/b6fcd20b-5ddd-4473-a7fd-554b6a8fded9) | ![image](https://github.com/user-attachments/assets/92c59574-b84c-44d2-9ad4-f528937d1fe2) |
> chore: add early return when there are no reviews to prevent invalid enhanced results

- .changeset/healthy-lies-act.md
- packages/magento-store/utils/redirectOrNotFound.ts
When resolving an url `foo.html` inside `redirectOrNotFound`, this change will always add `foo` to the list of candidates to look up, regardless of the current `StoreConfig.product_url_suffix` value.
This allows you to turn off the default `.html` URL suffix in Magento and still have the old URLs redirect correctly.
> Handle the case where one switches from using the default .html URL suffix, to not using one

- .changeset/itchy-waves-brush.md
- packages/magento-store/utils/redirectOrNotFound.ts
This enhances previous PR https://github.com/graphcommerce-org/graphcommerce/pull/2373 to use a permanent redirect when this can't be determined by routeData.
I think for old .html suffix handling and /p/ redirects this is the desired behavior for SEO 🤔
> Default to permanent redirects unless specified

- packages/ecommerce-ui/components/FormComponents/ActionCardListForm.tsx
- packages/magento-product-configurable/components/ConfigurableProductOptions/ConfigurableProductOptions.tsx
The `disableDeselectOption ` boolean can be used to ensure that users are unable to deselect options within a configurable product. By setting `disableDeselectOption ` to `true`, as in the example below, any selected option will remain selected, preventing users from accidentally or intentionally clearing their choice.
**Usage:**
```
<ConfigurableProductOptions product={product} disableDeselectOption />
```
> add disableDeselectOption boolean to prevent users from deselecting configurable options (GCOM-1507)

- .changeset/fifty-moose-laugh.md
- examples/magento-graphcms/pages/checkout/success.tsx
- packages/next-ui/Layout/components/LayoutHeader.tsx
- packages/next-ui/Layout/components/LayoutHeaderBack.tsx
In some cases, you may want to force the use of the 'up' data for the 'back' button, like the checkout success page. 
This boolean ensures that the 'up' data is always used.
> chore(GCOM-1490): add ‘preventClickBack’ boolean to optionally disable back navigation

- .changeset/purple-suns-unite.md
- packages/next-ui/Layout/components/LayoutHeaderBack.tsx
Resolves the following error:
```
React does not recognize the disableBackNavigation prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase disablebacknavigation instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
> refactor: exclude ‘disableBackNavigation’ prop from LinkOrButton in LayoutHeaderBack

- .changeset/gorgeous-ears-walk.md
- packages/image/components/Image.tsx
Serve smaller images by default, because there are only a list of image sizes to choose from.
> Solve an issue where image sizes are served in higher resolution than expected.

- .changeset/soft-turtles-float.md
- packages/ecommerce-ui/components/FormComponents/NumberFieldElement.tsx
- This resolves the following error when NumberFieldElement has InputProps:
`<NumberFieldElement InputProps={{ disableUnderline: true }} />`
```
Warning: React does not recognize the `disableUnderline` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `disableunderline` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack
```
> refactor: Destructure InputProps to ensure they are passed only to relevant components.

- .changeset/pink-goats-shop.md
- packages/ecommerce-ui/components/FormComponents/NumberFieldElement.tsx
The `disableUnderline` prop is only available in the `Input` and `FilledInput` variants, not in `OutlinedInput`.
See docs for reference:
- [FilledInput (filled)](https://mui.com/material-ui/api/filled-input/#props)
- [OutlinedInput (outlined)](https://mui.com/material-ui/api/outlined-input/#props)
- [Input (standard)](https://mui.com/material-ui/api/input/#props)
> chore: Omit disableUnderline prop for ‘outlined’ variant, because its not supported.

- .changeset/olive-windows-tickle.md
- packages/magento-customer/hooks/useAccountSignInUpForm.tsx
Fix session expired email not always available in cache
- use UseCustomerValidateTokenDocument instead of CustomerDocument to find email in cache
> fix(GCOM) session expired email not always available form cache

- .changeset/quiet-trains-grab.md
- packages/next-ui/FramerScroller/SidebarGallery.tsx
When de sidebar contains a long (wrapped) title, the title would stretch the size of the sidebar and cause the zoomed gallery to occupy only part of the viewport instead of zooming to fullscreen
> Fixed gallery zoom breaking on long sidebar content

- .changeset/soft-islands-hear.md
- packages/magento-product-configurable/components/ConfigurableProductOptions/ConfigurableProductOptions.tsx
Fix to respect the position of configurable product options by the attribute 'position' field populated in the Magento admin
> fix: respect configurable product option positions
