.changeset/big-pots-juggle.md
examples/magento-graphcms/pages/[...url].tsx
packages/magento-category/components/CategoryMeta/CategoryMeta.tsx

Unique meta title and description

fix: add page number to meta title and description

---

.changeset/short-rocks-study.md
examples/magento-graphcms/pages/wishlist/index.tsx
packages/magento-wishlist/README.md

fix: error when adding downloadable product to cart in wishlist

---

.changeset/stupid-stingrays-reply.md
packages/lingui-next/package.json

fix: Error: useLingui hook was used without I18nProvider

---

.changeset/itchy-singers-own.md
packages/magento-store/components/StoreSwitcherList/StoreSwitcherList.tsx

reverts: https://github.com/graphcommerce-org/graphcommerce/commit/65ea397ec53aa27f545b43feda8e35227e119ebe

fix: Stores weren't clickable in the /store-switcher

---

.changeset/angry-cows-jam.md
.changeset/large-dots-compare.md
.changeset/mighty-trains-talk.md
.changeset/plenty-melons-knock.md
.changeset/slimy-readers-sell.md
.changeset/slow-dodos-tie.md

This reverts commit c502d1e69fe140f2db2d0f4c5bc890d082a37527.

Revert "ci(changesets): versions updated"

---

.changeset/old-gifts-warn.md
examples/magento-graphcms/next-sitemap.config.js

Prevent deployment failing when not running on Vercel

fix: gracefully handle env var not existing

---

.changeset/tame-fireants-repeat.md
packages/next-ui/Navigation/components/NavigationItem.tsx
packages/next-ui/Navigation/components/NavigationOverlay.tsx
packages/next-ui/Navigation/components/NavigationProvider.tsx
packages/next-ui/Navigation/hooks/useNavigation.ts
packages/next-ui/Overlay/components/OverlayBase.tsx
packages/next-ui/Overlay/hooks/useOverlayPosition.ts

Fix issue where Navigation can't be reopened after closing, dragging or navigating

Fix: Navigation in DOM

---

.changeset/forty-apples-mate.md

Magento product compare functionality added (release notes)

---

.changeset/proud-crabs-end.md
examples/magento-graphcms/components/Layout/LayoutNavigation.tsx
packages/magento-customer/components/CustomerMenuFabItem/CustomerMenuFabItem.tsx
packages/magento-search/components/SearchLink/SearchLink.tsx
packages/magento-wishlist/components/WishlistMenuFabItem/WishlistMenuFabItem.tsx
packages/next-ui/LayoutParts/MenuFabSecondaryItem.tsx

- Fix closing the menu when clicking on search
- Add the option to close the menu when clicking on secondary menu items

fix: close menu on search and secondary menu items

---

.changeset/tough-apples-leave.md
packages/magento-customer/components/AccountSignInUpForm/AccountSignInUpForm.tsx

URL: https://graphcommerce.vercel.app/account/signin
The loading animation is not aligned correctly.
Current situation:
https://github.com/graphcommerce-org/graphcommerce/assets/62989724/e53ee7f2-e389-47ee-837b-6d09ba710f63
After:
https://github.com/graphcommerce-org/graphcommerce/assets/62989724/a77caec3-987b-464b-8ee5-2c1a935431fd

chore: Ensure correct width for CircularProgress and fix misalignment in rotate animation

---

.changeset/hot-schools-hunt.md
examples/magento-graphcms/package.json
packages/cli/package.json
packages/graphql-mesh/package.json
packages/graphql/package.json
packages/hygraph-cli/package.json
packages/react-hook-form/package.json
packagesDev/graphql-codegen-markdown-docs/package.json
packagesDev/graphql-codegen-near-operation-file/package.json
packagesDev/graphql-codegen-relay-optimizer-plugin/package.json
yarn.lock

fix: upgrade graphql to 16.7.1

---

.changeset/small-goats-hug.md
packages/next-ui/Overlay/components/OverlayBase.tsx

Overlays should only close after releasing pointer

Fixed overlays closing while still dragging

---

.changeset/red-gifts-listen.md
packages/framer-scroller/components/ScrollerButton.tsx
packages/next-ui/FramerScroller/ItemScroller.tsx
packages/next-ui/FramerScroller/SidebarGallery.tsx
packages/next-ui/FramerScroller/SidebarSlider.tsx
packages/next-ui/Row/RowLinks/RowLinks.tsx

https://hoproj.atlassian.net/browse/GCOM-1242

Add showButtons to scrollerButton instead of RowLinks (GCOM-1242)

---

.changeset/serious-wasps-itch.md
packages/magento-product/components/ProductPageDescription/ProductPageDescription.tsx

https://hoproj.atlassian.net/browse/GCOM-1248

Fix maxWidth on productPageDescription (GCOM-1248) 

---

.changeset/six-horses-repeat.md
examples/magento-graphcms/locales/de.po
examples/magento-graphcms/locales/en.po
examples/magento-graphcms/locales/es.po
examples/magento-graphcms/locales/fr.po
examples/magento-graphcms/locales/it.po
examples/magento-graphcms/locales/nl.po
packages/magento-customer/components/UpdateCustomerEmailForm/UpdateCustomerEmailForm.tsx

https://hoproj.atlassian.net/browse/GCOM-1251

fix current email translation (GCOM-1251)

---

.changeset/stupid-mice-check.md
packages/hygraph-cli/src/migrationAction.ts

[Ticket](https://hoproj.atlassian.net/browse/GCOM-1250)
[Blocks GCOM-535](https://hoproj.atlassian.net/browse/GCOM-535)

GCOM-1250 | Add support for updating and deleting enumerations (Hygraph CLI) 

---

packages/magento-customer/components/OrderItem/OrderItem.graphql
packages/magento-customer/components/OrderItem/OrderItem.tsx

[Ticket](https://hoproj.atlassian.net/browse/GCOM-1259)
- Deprecated product URL on Order Detail page

Fix/gcom 1259 | Deprecated product URL on Order Detail page

---

.changeset/fresh-games-roll.md
packagesDev/next-config/dist/withGraphCommerce.js
packagesDev/next-config/src/withGraphCommerce.ts

Added @graphcommerce packages in node_modules to nextjs watch options

[GCOM-1247] | next-config watch options

---

.changeset/chilled-pens-mate.md
packages/hygraph-ui/components/RichText/defaultRenderers.tsx
packages/hygraph-ui/components/RichText/types.ts

Ticket: https://hoproj.atlassian.net/browse/VR-1001
PR: https://github.com/ho-nl/project-verdouw-gc/pull/414

Add alt text to image inside richt text

---

.changeset/friendly-birds-scream.md
packages/magento-customer/components/AccountOrders/AccountOrders.graphql
packages/magento-customer/components/AccountOrders/AccountOrders.tsx
packages/magento-customer/graphql/AccountDashboardOrders.graphql

This reverts commit 816d7893159528bbe4ffc51c3958c806b81b58b0. This breaks compatibility with Magento 2.4.5

Revert "feat(GCOM-1316): change customer order sorting in Descending rder from Created at date

---

.changeset/rotten-rules-reflect.md
packages/framer-next-pages/components/Page.tsx
packages/next-ui/Overlay/components/OverlayBase.tsx

Property 'inert' must be of type 'boolean | undefined', but here has type '"true" | undefined'.
source: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

chore: apply correct type for the inert property

---

.changeset/olive-pumas-perform.md
examples/magento-graphcms/locales/nl.po
examples/magento-graphcms/pages/account/forgot-password.tsx

**Before:** https://app.birdeatsbug.com/DDTmvA6VvVIQqAO5Xlf4lIpaF2x0ytNQinTi-pc0IOku
**After:** https://app.birdeatsbug.com/OiU2BPgY6gD7OpTgIq42S3K86Ag-eS45yWtTASkQ-aKY

Resolve the overlay issue when navigating from the 'Forgot Password' page to the 'Sign In' page. (GCOM-1396)

---

.changeset/poor-masks-learn.md
packages/react-hook-form/package.json
packages/react-hook-form/src/useFormGql.tsx
yarn.lock

fix: wrap onComplete and onBeforeSubmit in useEventCallback

---

.changeset/spotty-falcons-grab.md
docs/contributing.md

Small PR - Commit 9bdfa2d4dfa9908b3068872c17485daffd029165 moved the types `vscode.md` file. This PR adjusts sources to changes.

Update VSCode guide reference

---

.changeset/heavy-balloons-confess.md
docs/hygraph/readme.md

New users would currently get stuck here

Add correct link to demo project

---

.changeset/silver-dolphins-serve.md
packages/magento-cart/components/CartFab/CartFab.tsx
packages/magento-compare/components/CompareFab.tsx
packages/magento-compare/components/CompareProductToggle.tsx
packages/magento-customer/components/CustomerFab/CustomerFab.tsx
packages/magento-customer/components/CustomerMenuFabItem/CustomerMenuFabItem.tsx
packages/magento-wishlist/components/WishlistFab/WishlistFab.tsx
packages/magento-wishlist/components/WishlistMenuFabItem/WishlistMenuFabItem.tsx

Remove all usages of the NoSsr component as the GraphQL layer already  handles this.

---

.changeset/quick-emus-end.md
packages/ecommerce-ui/components/FormComponents/ActionCardListForm.tsx
packages/ecommerce-ui/components/FormComponents/CheckboxButtonGroup.tsx
packages/ecommerce-ui/components/FormComponents/CheckboxElement.tsx
packages/ecommerce-ui/components/FormComponents/InputBaseElement.tsx
packages/ecommerce-ui/components/FormComponents/MultiSelectElement.tsx
packages/ecommerce-ui/components/FormComponents/NumberFieldElement.tsx
packages/ecommerce-ui/components/FormComponents/RadioButtonGroup.tsx
packages/ecommerce-ui/components/FormComponents/SliderElement.tsx
packages/ecommerce-ui/components/FormComponents/SwitchElement.tsx
packages/ecommerce-ui/components/FormComponents/TextFieldElement.tsx
packages/ecommerce-ui/components/FormComponents/ToggleButtonGroup.tsx

Related issue: https://github.com/react-hook-form/react-hook-form/issues/12758

Fix form submission issue by removing disabled prop from form controllers
